name: Publish to Dockerhub

on:
  push:
    branches:
      - master
      - GithubBuildAction

  release:
    types: [published]

jobs:
  push_to_registry:
    if: github.repository == 'MatthiasZepper/vocage'
    name: Push Docker image to Docker Hub / GitHub Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Change repo name to lowercase
        run: |
          REPO_LOWERCASE=${GITHUB_REPOSITORY,,}
          echo "${REPO_LOWERCASE}" >>${GITHUB_ENV}
          echo "REPOTITLE_LOWERCASE=$(basename $REPO_LOWERCASE)" >>${GITHUB_ENV}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push dev image
        uses: docker/build-push-action@v2
        if: github.event_name == 'push'
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOTITLE_LOWERCASE }}:dev
            ghcr.io/${{ env.REPO_LOWERCASE }}:dev
            
      - name: Push release image
        uses: docker/build-push-action@v2
        if: github.event_name == 'release'
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOTITLE_LOWERCASE }}:${{ github.event.release.tag_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOTITLE_LOWERCASE }}:latest
            ghcr.io/${{ env.REPO_LOWERCASE }}:${{ github.event.release.tag_name }}
            ghcr.io/${{ env.REPO_LOWERCASE }}:${{ github.sha }}
            ghcr.io/${{ env.REPO_LOWERCASE }}:latest
