name: Test successful compilation on Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-gnu
    - name: Change repo name to lowercase
      run: |
        echo "REPO_LOWERCASE=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        echo ${{ env.REPO_LOWERCASE }}
        echo ${ REPO_LOWERCASE }
        echo "REPOTITLE_LOWERCASE=$(basename ${{ env.REPO_LOWERCASE }})" >>${GITHUB_ENV}
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: vocage_x86_64-unknown-linux-gnu
        path: /home/runner/work/vocage/vocage
